# Generated by Django 4.0.4 on 2022-05-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ingredientes', models.TextField(help_text='redacta los ingredientes')),
                ('preparacion', models.TextField()),
                ('autor', models.CharField(max_length=200)),
            ],
        ),
    ]
