# Generated by Django 4.0.4 on 2022-05-04 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_autor_receta_tiempo_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.autor'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='comentario')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.receta')),
            ],
        ),
    ]
