# Generated by Django 3.2 on 2022-05-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_cliente_pedido_pedidodetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('pagado', 'Pagado')], default='solicitado', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nro_recibo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
